version: "3.8"

services:
  backend:
    build: ./Backend
    container_name: crud_backend
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend_builder:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend_builder
    volumes:
      - frontend_build:/app/build
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend_builder
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local
  frontend_build:
    driver: local

networks:
  app-network:
    driver: bridge
