version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8080"
    env_file:
      - .env
    environment:
      - MongoUrl=${mongoDb}

  frontend:
    build: ./frontend
    container_name: frontend
    # Build the frontend into a named volume so nginx can serve it
    volumes:
      - frontend_build:/app/build
    command: sh -c "npm run build && sleep 1"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  frontend_build:
    driver: local
